CREATE DATABASE geko5 CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE USER db_user IDENTIFIED BY 'db_password';
GRANT ALL PRIVILEGES ON geko5.* TO geko5@localhost WITH GRANT OPTION;
FLUSH PRIVILEGES;

