name: React Frontend Build

on: pull_request

jobs:
  build-react:
    runs-on: ubuntu-latest
    
    strategy:
        matrix:
            node-version: [20.x]
           #node-version: [16.x, 18.x, 20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

    #   - name: Upload coverage to Codecov
    #     uses: codecov/codecov-action@v1

      - name: Install dependencies
        working-directory: Geko5-frontend  # Sostituisci con la cartella del tuo frontend
        # run: npm install --save-dev babel-jest @babel/plugin-proposal-private-property-in-object @babel/preset-env @babel/preset-react @babel/plugin-proposal-export-namespace-from identity-obj-proxy d3-array d3-scale --legacy-peer-deps
        run: npm install --save-dev babel-jest @babel/plugin-proposal-private-property-in-object --legacy-peer-deps

    #   - name: Run tests with coverage report
    #     working-directory: Geko5-frontendd  # Sostituisci con la cartella del tuo frontend
    #     env:
    #       CI: false
    #     # run: npm test -- --coverage --transformIgnorePatterns "node_modules/(?!axios|d3-scale|d3-array|@mui/x-charts)"
    #     run: npm test -- --coverage

      - name: Build React app
        working-directory: Geko5-frontend  # Sostituisci con la cartella del tuo frontend  env:
        env:
          CI: false
        run: npm run build -- --verbose